### ISSUE TITLE
SAXNotSupportedException: validation is not supported

### ISSUE THREAD

**Issue by fml2** [dom4j/dom4j#111]
If I include the `2.1.3` version of Dom4j into my project, then a library that uses DOM parsing throws an exception:

```
Caused by: org.xml.sax.SAXNotSupportedException: validation is not supported
	at org.gjt.xpp.sax2.Driver.setFeature(Driver.java:166)
	at org.gjt.xpp.jaxp11.SAXParserImpl.<init>(SAXParserImpl.java:123)
	at org.gjt.xpp.jaxp11.SAXParserFactoryImpl.newSAXParserImpl(SAXParserFactoryImpl.java:114)
	at org.gjt.xpp.jaxp11.SAXParserFactoryImpl.setFeature(SAXParserFactoryImpl.java:142)
```

With the version `2.1.1` the problem does not occur.

**Comment by nbaztec** [comment]
having the same issue. Downgrading to `2.1.1` fixed this. The defaulting line in my case was:
```
        reader.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false)
```

Seems for some reason `org.gjt.xpp.sax2.Driver` is being used instead of jvm xml driver.
