### ISSUE TITLE
Getting error: premature end of file!

### ISSUE THREAD

**Issue by ahmedmohiduet** [dom4j/dom4j#19]
so my test codes:
    @Test
    public void testXmlParsing() {
    String queryUrl="https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?cmd=prlinks&dbfrom=pubmed&retmode=ref*&id=24919618,24919617,24919616,24919615,24919614,24919613,24919612,24919611,24919610,24919609,24919608,24919607,24919606,24919605,24919498,24919497,24919496,24919495,24919494,24919493,24919492,24919491,24919490,24919489,24919488,24919410,24919159,24918970,24918969,24918833,24918767,24918729,24918728,24918727,24918726,24918725,24918724,24918723,24918722,24918721,24918720,24918719,24918718,24918643,24918496,24918428,24918424,24918423,24918422,24918421,24918420,24918419,24918418,24918417,24918416,24918415,24918414,24918413,24918412,24918411,24918410,24918409,24918408,24918407,24918406,24918405,24918404,24918269,24918023,24918022,24917638,24917637,24917636,24917635,24917634,24917633,24917632,24917631,24917625,24917624,24917553,24917539,24917516,24917514,24917511,24917458,24917275,24917270,24917261,24917260,24917259,24917258,24917257,24917256,24917255,24917254,24917253,24917252,24917174,24916892,24916828,24916768,24916659,24916410,24916408,24916369,24916160,24916159,24916158,24916091,24916090,24916089,24916088,24916087,24916086,24916085,24916013,24916012,24915882,24915656,24915540,24915460,24915257,24915210,24915161,24915045,24914850,24914849,24914848,24914847,24914846,24914845,24914844,24914843,24914842,24914841,24914840,24914839,24914838,24914837,24914836,24914835,24914711,24914710,24914533,24913954,24913953,24913952,24913951,24913950,24913949,24913948,24913947,24913946,24913945,24913944,24913943,24913942,24913941,24913815,24913655,24913598,24913327,24913326,24913138,24913029,24913016,24912753,24912618,24912493,24912492,24912443,24911958,24911862,24911861,24911860,24911859,24911858,24911857,24911856,24911855,24911854,24911853,24911852,24911851,24911850,24911849,24911848,24911847,24911846,24911845,24911844,24911843,24911814,24911631,24911460,24911348,24911257,24911223,24911221,24911115,24911019,24910429,24910422,24910421,24910399,24910328,24910171,24910128,24909993,24909941,24909896,24909737,24909579,24909510,24909444,24909443,24909383,24909374,24909329,24909328,24909327,24909326,24909325,24909324,24909323,24909322,24909321,24909261,24909233,24909181,24909159,24909122,24909111,24908708,24908591,24908558,24908518,24908474,24908184,24908183,24908182,24908162,24908075,24908074,24907887,24907885,24907846,24907842,24907838,24907836,24907833,24907832,24907828,24907822,24907821,24907820,24907819,24907818,24907817,24907815,24907810,24907809,24907804,24907800,24907799,24907798,24907784,24907711,24907710,24907363,24907248,24907247,24907246,24907245,24907244,24907243,24907106,24907022,24907021,24906986,24906889,24906796,24906497,24906496,24906472,24906471,24906470,24906430,24906291,24906161,24906132,24906122,24906118,24906009,24906001,24905998,24905925,24905918,24905856,24905834,24905826,24905820,24905805,24905764,24905740,24905738,24905728,24905590,24905579,24905578,24905468,24905459,24905447,2490544,24905362,24905361,24905353,24905232,24905231,24905191,24905132,24905116,24905100,24905098,24905026,24905024,24905014,24904072,24904071,24904070,24904069,24904068,24904066,24904065,24903807,24903598,24903597,24903584,24903493,24903492,24903241,24903240,24903239,24902821,24902736,24902735,24902734,24902733,24902732,24902731,24902730,24902729,24902728,24902727,24902726,24902725,24902724,24902691,24902690,24902689,24902688,24902684,24902669,24902105,24902104,24902103,24902102,24902101,24902100,24902099,24902098,24902097,24902096,24902095,24902094,24902093,24902092,24902091,24902090,24902089,24902088,24902087,24902086,24901951,24901936,24901887,24901886,24901885,24901884,24901883,24901564,24901442,24901304,24901061,24901060,24901059,24901058,24901057,24899635,24899500,24899462,24899219,24899087,24899086,24898902,24898853,24898793,24898627,24898580,24898467,24898107,24898091,24898090,24898089,24898088,24898087,24898086,24898085,24898084,24897978,24897977,24897976,24897975,24897974,24897973,24897972,24897971,24897970,24897969,24897968,24897967,24897966,24897965,24897964,24897760,24897495,24897494,24897493,24897492,24897491,24897490,24897489,24897488,24897487,24897486,24897485,24897484,24897483,24897482,24897481,24897480,24897479,24897478,24897477,24897476,24897475,24897474,24897473,24897472,24897471,24897470,24897469,24897468,24897467,24897466,24897394,24897345,24897031,24897019,24897018,24897017,24897016,24897015,24897014,24897013,24897012,24896581,24896580,24896579,24896578,24896577,24896576,24896575,24896574,24896573,24896572,24896571,24896570,24896372,24896313,24896312,24896311,24896310,24896309,24896308,24896262,24896261,24896229,24895958,";
        URL url = null;
        try {
            url = new URL(queryUrl);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        HttpURLConnection.setFollowRedirects(true);
        HttpURLConnection huc = null;
        try {
            huc = (HttpURLConnection) url.openConnection();
        } catch (IOException e) {
            e.printStackTrace();
        }
        huc.setConnectTimeout(30*60*1000);
        try {
            huc.setRequestMethod("GET");
        } catch (ProtocolException e) {
            e.printStackTrace();
        }
        huc.addRequestProperty("Accept-Charset", "UTF-8");
        huc.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36");
        huc.setRequestProperty("Connection", "keep-alive");

        huc.setInstanceFollowRedirects(true);
        try {
            huc.connect();
        } catch (IOException e) {
            e.printStackTrace();
        }

        InputStream is= null;
        try {
            is = huc.getInputStream();
        } catch (IOException e) {
            e.printStackTrace();
        }
        String theString = null;
        try {
            theString = IOUtils.toString(is, "UTF-8");
        } catch (IOException e) {
            e.printStackTrace();
        }
        System.out.println(theString);
        SAXReader reader=new SAXReader();
        try {
            Document doc=reader.read(is);
        } catch (DocumentException e) {
            e.printStackTrace();
        }
        assertTrue(true);
    }

My intellij giving me : premature end of file error for my code:
org.dom4j.DocumentException: Error on line 1 of document  : Premature end of file. Nested exception: Premature end of file.
	at org.dom4j.io.SAXReader.read(SAXReader.java:482)
	at org.dom4j.io.SAXReader.read(SAXReader.java:343)
	at com.vantage.iseek.incremental.indexer.impl.GalaxyXmlParsingTest.testXmlParsing(GalaxyXmlParsingTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:73)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:46)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:180)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:41)
	at org.junit.runners.ParentRunner$1.evaluate(ParentRunner.java:173)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:220)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Nested exception: 
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1019)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.dom4j.io.SAXReader.read(SAXReader.java:465)
	at org.dom4j.io.SAXReader.read(SAXReader.java:343)
	at com.vantage.iseek.incremental.indexer.impl.GalaxyXmlParsingTest.testXmlParsing(GalaxyXmlParsingTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:73)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:46)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:180)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:41)
	at org.junit.runners.ParentRunner$1.evaluate(ParentRunner.java:173)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:220)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Nested exception: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1019)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.dom4j.io.SAXReader.read(SAXReader.java:465)
	at org.dom4j.io.SAXReader.read(SAXReader.java:343)
	at com.vantage.iseek.incremental.indexer.impl.GalaxyXmlParsingTest.testXmlParsing(GalaxyXmlParsingTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:73)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:46)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:180)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:41)
	at org.junit.runners.ParentRunner$1.evaluate(ParentRunner.java:173)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:220)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code 0

I had checked my xml via some online xml checking tools and found xml looking ok.
Can I avoid this error by any twaeking or something?

**Comment by FilipJirsak** [comment]
This is bug in your code.

```
 InputStream is= null;
    try {
        is = huc.getInputStream();
    } catch (IOException e) {
        e.printStackTrace();
    }
    String theString = null;
    try {
        theString = IOUtils.toString(is, "UTF-8");
    } catch (IOException e) {
        e.printStackTrace();
    }
    System.out.println(theString);
    SAXReader reader=new SAXReader();
    try {
        Document doc=reader.read(is);
    } catch (DocumentException e) {
        e.printStackTrace();
    }
```

On line `IOUtils.toString(is, "UTF-8")` you read the entire input stream data. After that pointer is at the end of file.

**Comment by ahmedmohiduet** [comment]
Thank you FilipJirsak!
