### ISSUE TITLE
External DTD crashes

### ISSUE THREAD

**Issue by fablue** [dom4j/dom4j#30]
Hey ☺️  I need to parse a document, which contains the following header

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
```

Which leads to the following stacktrace 

```
Exception in thread "main" org.dom4j.DocumentException: Error on line 31 of document http://www.w3.org/TR/html4/loose.dtd : Deklaration für Entity "HTML.Version" muss mit ">" enden. Nested exception: Deklaration für Entity "HTML.Version" muss mit ">" enden.
	at org.dom4j.io.SAXReader.read(SAXReader.java:482)
	at org.dom4j.io.SAXReader.read(SAXReader.java:264)
	at com.quickbirdstudios.muc.server.parse.BasicParser.parseDetailDetail_html(BasicParser.kt:51)
	at com.quickbirdstudios.muc.server.parse.BasicParser.parseDetails(BasicParser.kt:41)
	at com.quickbirdstudios.muc.server.parse.BasicParser.parseMuscle(BasicParser.kt:24)
	at com.quickbirdstudios.muc.server.parse.BasicParser.parse(BasicParser.kt:17)
	at com.quickbirdstudios.muc.server.MainKt.main(Main.kt:14)
Nested exception: 
org.xml.sax.SAXParseException; systemId: http://www.w3.org/TR/html4/loose.dtd; lineNumber: 31; columnNumber: 3; Deklaration für Entity "HTML.Version" muss mit ">" enden.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.scanEntityDecl(XMLDTDScannerImpl.java:1604)
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.scanDecls(XMLDTDScannerImpl.java:2028)
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.scanDTDExternalSubset(XMLDTDScannerImpl.java:306)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1174)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1045)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:959)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.dom4j.io.SAXReader.read(SAXReader.java:465)
	at org.dom4j.io.SAXReader.read(SAXReader.java:264)
```

I tried to do 

```kotlin
        parser.isIncludeInternalDTDDeclarations= false
        parser.isIncludeExternalDTDDeclarations= false
```

which had no effect for me. How can I prevent the parser from following the link?

**Comment by FilipJirsak** [comment]
This is not a matter of dom4j, it is a matter of the SAX parser (default Xerces in your case). I think your problem is that you are trying to parse HTML using XML parser - it's not possible, HTML is not XML. 
There are some Java HTML parsers, for example:
* https://jsoup.org/
* http://htmlcleaner.sourceforge.net/
* https://about.validator.nu/htmlparser/
* http://jtidy.sourceforge.net/
* http://jericho.htmlparser.net/docs/index.html
* http://htmlparser.sourceforge.net/
* https://jodd.org/lagarto/
* http://nekohtml.sourceforge.net/
* http://jaunt-api.com/
* http://htmlunit.sourceforge.net/

But there is no way to use any of them directly with dom4j nowadays.
