### ISSUE TITLE
java.lang.NoClassDefFoundError: org/jaxen/JaxenException

### ISSUE THREAD

**Issue by JuKu** [dom4j/dom4j#60]
Hi,

if i execute this code:
```java
Document doc = getDoc(file);

//get all tilesets
List<Node> tilesetNodes = doc.selectNodes("/map/tileset"); //<-- this line throws the exception
```

i get this exception:
```java
java.lang.NoClassDefFoundError: org/jaxen/JaxenException

	at org.dom4j.DocumentFactory.createXPath(DocumentFactory.java:222)
	at org.dom4j.tree.AbstractNode.createXPath(AbstractNode.java:202)
	at org.dom4j.tree.AbstractNode.selectNodes(AbstractNode.java:159)
	at com.jukusoft.mmo.engine.shared.map.parser.TmxParser.parse(TmxParser.java:66)
	at com.jukusoft.mmo.engine.shared.map.parser.TmxMapParser.parse(TmxMapParser.java:54)
	at com.jukusoft.mmo.engine.shared.map.parser.TmxMapParserTest.testParse(TmxMapParserTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: org.jaxen.JaxenException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more
```

How can is fix this?
I am using **version 2.1.1** of dom4j.

**Comment by FilipJirsak** [comment]
Hi, add [Jaxen ](https://search.maven.org/artifact/jaxen/jaxen/1.1.6/bundle) to your project runtime dependencies.

**Comment by JuKu** [comment]
@FilipJirsak Thanks for your fast answer!
It works now.

**Comment by sporkisfaster** [comment]
So I'm tinkering with this for a project and for someone that has never worked with dom4j I think it would be much more helpful to mention this fact in the documentation in places such as here:https://github.com/dom4j/dom4j/wiki/Cookbook under "Using XPath" and https://dom4j.github.io/ under "Powerful navigation with XPath" this is not obvious in the slightest.
