### ISSUE TITLE
Error in saxreader.read(URL) method dom4j 2.1.1 version running on java 8U181

### ISSUE THREAD

**Issue by imsmajor** [dom4j/dom4j#61]
I am having a sax reader exception from dom4j 2.1.1 it was working with dom4j 1.6 version, i see some features are disabled for parsing can you please help.

Caused by: org.dom4j.DocumentException
	at org.dom4j.io.SAXReader.read(SAXReader.java:464)
	at org.dom4j.io.SAXReader.read(SAXReader.java:273)

**Comment by dmigowski** [comment]
See https://github.com/dom4j/dom4j/releases:

If you use some optional dependency of dom4j (for example Jaxen, xsdlib etc.), you need to specify an explicit dependency on it in your project. They are no longer marked as a mandatory transitive dependency by dom4j.
Following SAX parser features are disabled by default in DocumentHelper.parse() for security reasons (they were enabled in previous versions):
http://xml.org/sax/properties/external-general-entities
http://xml.org/sax/properties/external-parameter-entities
