### ISSUE TITLE
org.dom4j.tree.AbstractNode.selectNodes(AbstractNode.java:166) causes ConcurrentModificationException

### ISSUE THREAD

**Issue by Golyshkin** [dom4j/dom4j#81]
I am using Dom4J v.1.6.1 and during selecting nodes from multiple threads (used for reducing time) randomly I am observing following exception:

```
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at org.jaxen.util.DescendantAxisIterator.next(DescendantAxisIterator.java:111)
	at org.jaxen.expr.DefaultStep.evaluate(DefaultStep.java:157)
	at org.jaxen.expr.DefaultLocationPath.evaluate(DefaultLocationPath.java:151)
	at org.jaxen.expr.DefaultAbsoluteLocationPath.evaluate(DefaultAbsoluteLocationPath.java:117)
	at org.jaxen.expr.DefaultXPathExpr.asList(DefaultXPathExpr.java:108)
	at org.jaxen.BaseXPath.selectNodesForContext(BaseXPath.java:692)
	at org.jaxen.BaseXPath.selectNodes(BaseXPath.java:229)
	at org.dom4j.xpath.DefaultXPath.selectNodes(DefaultXPath.java:132)
	at org.dom4j.tree.AbstractNode.selectNodes(AbstractNode.java:166)
	at com.anritsu.eu.rtd.engine.upgrade.XPathExecutionController$XpathExecutorTask.compute(XPathExecutionController.java:196)
	at com.anritsu.eu.rtd.engine.upgrade.XPathExecutionController$XpathExecutorTask.compute(XPathExecutionController.java:178)
	at java.util.concurrent.RecursiveTask.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.execTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.util.concurrent.ForkJoinPool.work(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```
Looks like it happened from Dom4J because it using internally a simple **ArrayList** instead of **CopyOnWriteArrayList**. My source code which is causing such issue is below:

```java
   private class XpathExecutorTask extends RecursiveTask<List<Element>>
   {
      private static final long serialVersionUID = 4910472337178774214L;
      private Stack<String> m_StackXPaths;

      XpathExecutorTask( Stack<String> aStackXPaths )
      {
         m_StackXPaths = aStackXPaths;
      }

      @Override
      protected List<Element> compute()
      {
         long time = System.currentTimeMillis();

         String xPath = m_StackXPaths.pop();

Line:196:    List<Element> retList = new ArrayList<>( m_Document.selectNodes( xPath ) );

         if ( !m_StackXPaths.isEmpty() )
         {
            retList.addAll( m_Document.selectNodes( xPath ) );
            retList.addAll( new XpathExecutorTask( m_StackXPaths ).fork().join() );
         }

         LOGGER.info( String.format( "Time spent [%.2f] for xPath query [%s]", (float)( System.currentTimeMillis() - time ) / 1000, xPath ) );

         return retList;
      }
   }
```

Can you suggest something or confirm that the latest Dom4J has no such bug?

**Comment by FilipJirsak** [comment]
The default implementation is based on AbstractNode and uses ArrayList. The ArrayList is not thread-safe so it can't be used for writing in multiple threads. You can either implement dom4j interfaces by yourself (you can base it on `AbstractNode` and other `Abstract*` classes and override `createContentList()` methods) either protect access to the whole document with a lock.
