### ISSUE TITLE
Dom4j 2.1.3 Conflict with POI 4.12

### ISSUE THREAD

**Issue by zxc2020789** [dom4j/dom4j#88]
Dom4j 2.1.1 Can be used normally

Dom4j 2.1.3 Conflict with POI 4.12 . Error
```
Error: handleBadRequest StackTrace : java.lang.RuntimeException: not supported setting property http://xml.org/sax/properties/lexical-handler
	at org.apache.xmlbeans.impl.store.Locale$SaxLoader.<init>(Locale.java:3397)
	at org.apache.xmlbeans.impl.store.Locale$XmlReaderSaxLoader.<init>(Locale.java:3087)
	at org.apache.xmlbeans.impl.store.Locale.getSaxLoader(Locale.java:3072)
	at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1272)
	at org.apache.xmlbeans.impl.store.Locale.parseToXmlObject(Locale.java:1259)
	at org.apache.xmlbeans.impl.schema.SchemaTypeLoaderBase.parse(SchemaTypeLoaderBase.java:345)
	at org.openxmlformats.schemas.drawingml.x2006.main.ThemeDocument$Factory.parse(Unknown Source)
	at org.apache.poi.xssf.model.ThemesTable.<init>(ThemesTable.java:86)
	at org.apache.poi.ooxml.POIXMLFactory.createDocumentPart(POIXMLFactory.java:61)
	at org.apache.poi.ooxml.POIXMLDocumentPart.read(POIXMLDocumentPart.java:684)
	at org.apache.poi.ooxml.POIXMLDocument.load(POIXMLDocument.java:180)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:288)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:309)
```

**Comment by FilipJirsak** [comment]
This is probably due to #85. I'll release version 2.1.4 within few days where dependencies will be optional again.

**Comment by zxc2020789** [comment]
Thank you for your reply
