### ISSUE TITLE
[bug] error in parsing XSD.

### ISSUE THREAD

**Issue by XenoAmess** [dom4j/dom4j#93]
I do think XSD is xml (in format), so I tried to parse a XSD string using DocumentHelper.parseText() function.
But I got an error with it.
the XSD file is:
```
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3school.com.cn"
           xmlns="http://www.w3school.com.cn"
           elementFormDefault="qualified">

    <xs:element name="note">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="to" type="xs:string"/>
                <xs:element name="from" type="xs:string"/>
                <xs:element name="heading" type="xs:string"/>
                <xs:element name="body" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
```
I don't see it violate any xml rule, but simply, it cause an error when using DocumentHelper.parseText().
the error chain looks like:
```
java.io.IOException: org.dom4j.DocumentException: SAX2 driver class org.apache.xerces.parsers.SAXParser does not implement XMLReader
	at com.xenoamess.x8l.dealers.XmlDealer$1.read(XmlDealer.java:87)
	at com.xenoamess.x8l.dealers.XmlDealer$1.read(XmlDealer.java:75)
	at com.xenoamess.x8l.dealers.LanguageDealer.read(LanguageDealer.java:101)
	at com.xenoamess.x8l.ContentNode.read(ContentNode.java:582)
	at com.xenoamess.x8l.X8lTree.read(X8lTree.java:705)
	at com.xenoamess.x8l.X8lTree.read(X8lTree.java:679)
	at com.xenoamess.x8l.X8lTree.parse(X8lTree.java:740)
	at com.xenoamess.x8l.X8lTree.load(X8lTree.java:545)
	at com.xenoamess.x8l.X8lTree.load(X8lTree.java:486)
	at com.xenoamess.x8l.idea_plugin.actions.XmlGenerateX8lAction.loadX8lTreeFromEvent(XmlGenerateX8lAction.java:48)
	at com.xenoamess.x8l.idea_plugin.actions.AbstractX8lFileAction.actionPerformed(AbstractX8lFileAction.java:74)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:295)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:296)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:281)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:285)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:517)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:36)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:539)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6650)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6415)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5025)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:965)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:903)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:835)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:816)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.dom4j.DocumentException: SAX2 driver class org.apache.xerces.parsers.SAXParser does not implement XMLReader
	at org.dom4j.io.SAXReader.read(SAXReader.java:513)
	at org.dom4j.DocumentHelper.parseText(DocumentHelper.java:279)
	at com.xenoamess.x8l.dealers.XmlDealer$1.read(XmlDealer.java:80)
	... 60 more
Caused by: java.lang.ClassCastException: class org.apache.xerces.parsers.SAXParser cannot be cast to class org.xml.sax.XMLReader (org.apache.xerces.parsers.SAXParser is in unnamed module of loader com.intellij.util.lang.UrlClassLoader @d2cc05a; org.xml.sax.XMLReader is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @190ac542)
	at org.dom4j.io.SAXHelper.createXMLReader(SAXHelper.java:109)
	at org.dom4j.io.SAXReader.createXMLReader(SAXReader.java:896)
	at org.dom4j.io.SAXReader.getXMLReader(SAXReader.java:732)
	at org.dom4j.io.SAXReader.read(SAXReader.java:464)
	... 62 more
Exception "java.lang.ClassNotFoundException: com/intellij/codeInsight/editorActions/ReferenceData"while constructing DataFlavor for: application/x-java-jvm-local-objectref; class=com.intellij.codeInsight.editorActions.ReferenceData
Exception "java.lang.ClassNotFoundException: com/intellij/codeInsight/editorActions/ReferenceData"while constructing DataFlavor for: application/x-java-jvm-local-objectref; class=com.intellij.codeInsight.editorActions.ReferenceData
```

my related codes:

```
                    @Override
                    public boolean read(@NotNull Reader reader, @NotNull ContentNode contentNode) throws
                            IOException, X8lGrammarException {
                        try {
                            Document document = DocumentHelper.parseText(IOUtils.toString(reader));
                            XmlDealer.read(contentNode, document.getRootElement());
                        } catch (DocumentException e) {
                            throw new IOException(e);
                        }
                        return true;
                    }
```

**Comment by XenoAmess** [comment]
So, **if it is a bug:** 

please fix it, thanks.

**if it is by design:** 

please tell me two things.

1.how to parse a XSD file with dom4j correctly.

2. why the string I profided above is not a xml, and where did it violate xmls' which rule.

**Comment by XenoAmess** [comment]
My bad.
I found where it goes wrong.
Though I still cannot understand why you create a node for xmlns.
It is definitely an attribute, not child node.
Anyway,  I handled my lib to suit your design there.
Nothing wrong now.
