### ISSUE TITLE
Invalid Gradle Module Metadata - optional dependencies not optional

### ISSUE THREAD

**Issue by fransflippo** [dom4j/dom4j#99]
According to https://github.com/gradle/gradle/issues/13656#issuecomment-658873625 , dom4j has invalid Gradle Module Metadata which can cause projects with a dependency on dom4j to pull in the optional pull-parser:pull-parser:2 dependency as well. This parser seems to have some issues which can result in an error `org.xml.sax.XMLReader.setProperty("http://xml.org/sax/properties/lexical-handler", this)` that the default XML parser on the JVM doesn't throw.

Can you look at fixing the Gradle Module Metadata?

Thanks!

**Comment by robert-gurol-signavio** [comment]
Workarounds
* It's not a problem using Gradle 5, it seems
* You can add a hard exclude of this optional dependency like so (if that's an option for you): 
```
    implementation(group: 'org.dom4j', name: 'dom4j', version: "2.1.3") {
        exclude group: "pull-parser", module: "pull-parser"
    }
```
(Gradle, Groovy DSL)

**Comment by Vampire** [comment]
`exclude`s are actually not the semantically correct way to fix invalid metadata.
That's more symptom treatment, like calling `Thread.sleep` to "fix" multi-threading issues or `SwingUtilities.invokeLater` to "fix" GUI issues.
Instead component metadata rules should be the tool of choice.
As all dependencies are optional, a simple one would be:
```groovy
dependencies {
   components {
       withModule('org.dom4j:dom4j', ClearDependencies)
   }
}

class ClearDependencies implements ComponentMetadataRule {
   void execute(ComponentMetadataContext context) {
       context.details.allVariants { withDependencies { clear() } }
   }
}
```
(c) melix from https://github.com/gradle/gradle/issues/13656#issuecomment-658873625

**Comment by hoangcongtuan** [comment]
I have try and got an error at runtime

![image](https://user-images.githubusercontent.com/15606968/182056131-051b38fd-f361-49c6-8183-05c815c2c80a.png)


`2022-08-01 08:36:09.183 6826-6826/com.xxx.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx.dev, PID: 6826
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jaxen/dom4j/Dom4jXPath;
        at org.dom4j.xpath.DefaultXPath.parse(DefaultXPath.java:353)
        at org.dom4j.xpath.DefaultXPath.<init>(DefaultXPath.java:59)
        at org.dom4j.DocumentFactory.createXPath(DocumentFactory.java:222)
        at org.dom4j.tree.AbstractNode.createXPath(AbstractNode.java:202)
        at org.dom4j.tree.AbstractNode.selectNodes(AbstractNode.java:159)
        at xxx(my app package)
        at xxx(my app package)
        at xxx(my app package)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@48d11a8, Dispatchers.Main.immediate]
    Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jaxen.dom4j.Dom4jXPath" on path: DexPathList[[zip file "/data/app/~~iRsRncGn8L063hNDpVm64A==/xxx-PpfNVzHq5gt0ms5r9BNdZQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~iRsRncGn8L063hNDpVm64A==/xxx-PpfNVzHq5gt0ms5r9BNdZQ==/lib/arm64, /data/app/~~iRsRncGn8L063hNDpVm64A==/xxx-PpfNVzHq5gt0ms5r9BNdZQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 16 more`

**Comment by Vampire** [comment]
They are optional dependencies, not unnecessary dependencies. If you use the part that needs that dependency, you also need the dependency.

The quick and easy way is to add it as `runtimeOnly` dependency.
The semantically correct way would be to - either in the same or another component metadata rule - add a variant for that use-case and then depend on that variant.
